### ISSUE TITLE
Error on creating game

### ISSUE THREAD

**Issue by caspaas** [tlitookilakin/MUMPs#2]
Hi

Im getting [MUMPs] Failed to retrieve hijacked pytk display device, attempting default
[MUMPs] This mod failed in the GameLoop.SaveLoaded event. Technical details:
NullReferenceException: Object reference not set to an instance of an object.
at MUMPs.Props.LightingLayer.Reload() in C:\Users\Wren\source\repos\MUMPs\MUMPs\Props\LightingLayer.cs:line 41
at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

also you know where this is coming from?

Its on first game start.

using pytk latest. 1.23  (not the lite version)

Also how can I compile a new version? xD

**Comment by tlitookilakin** [comment]
Can I get a full log please?

I'll release an updated version later, but if you would like to compile it now, you will need to download the source and build it with Visual Studio.

**Comment by caspaas** [comment]
here you go ! 

https://smapi.io/log/a2dc54f924ea4d8791f608598febac07

Sorry if its a long one.
Big ass modpack. XD

**Comment by caspaas** [comment]
ITs going to sound dumb, sorry.
But updating to the new "lite version" of PYTK the error doesnt pop up anymore

**Comment by tlitookilakin** [comment]
Should be fixed now, but I'll test it later
