### ISSUE TITLE
Weird transpiler error

### ISSUE THREAD

**Issue by Cricket742** [tlitookilakin/MUMPs#3]
So I have MUMPS installed for Cape stardew, and upon loading up the game, I got this weird error. I went to the stardew discord channel for modded support and someone told me it was a transpiler error. Here's my log:  https://smapi.io/log/eb8a43c37b1043cd955c2a482fa22bdc (sorry it's long, the error should be near the end)

Thank you for putting the time in to work on this mod!

**Comment by tlitookilakin** [comment]
I'm sorry, I'm not sure how I missed this. The log is expired- if you are still having problems, can you please upload a new log with the error?

**Comment by Cricket742** [comment]
I added mumps back to test and did get the same error. Here's the log: https://smapi.io/log/c5b85267ec714fc5a86767c536f0ae7c

**Comment by tlitookilakin** [comment]
Looks like the same error as #4 so I'll move the discussion over there.
